local theme = require("base46.themes.everforest").base_30

vim.api.nvim_set_hl(0, "SnacksPickerBorder", { fg = theme.black })
vim.api.nvim_set_hl(0, "SnacksPickerCol", { fg = theme.vibrant_green })
vim.api.nvim_set_hl(0, "SnacksPickerDesc", { fg = theme.vibrant_green })
vim.api.nvim_set_hl(0, "SnacksPickerTree", { fg = theme.vibrant_green })
vim.api.nvim_set_hl(0, "SnacksPickerDir", { fg = theme.white })
vim.api.nvim_set_hl(0, "SnacksPickerFile", { fg = theme.orange })
vim.api.nvim_set_hl(0, "SnacksPickerMatch", { fg = theme.orange })
vim.api.nvim_set_hl(0, "SnacksDashboardDir", { fg = theme.white })
vim.api.nvim_set_hl(0, "SnacksDashboardFile", { fg = theme.yellow })
vim.api.nvim_set_hl(0, "SnacksDashboardIcon", { fg = theme.yellow })
vim.api.nvim_set_hl(0, "SnacksDashboardTitle", { fg = theme.orange })
vim.api.nvim_set_hl(0, "SnacksDashboardHeader", { fg = theme.orange })
vim.api.nvim_set_hl(0, "SnacksDashboardFooter", { fg = theme.orange })
vim.api.nvim_set_hl(0, "SnacksDashboardDesc", { fg = theme.orange })
vim.api.nvim_set_hl(0, "SnacksDashboardSpecial", { fg = theme.yellow })
vim.api.nvim_set_hl(0, "NoiceCmdlinePopupBorder", { fg = theme.green })
vim.api.nvim_set_hl(0, "NoiceCmdlineIconCmdline", { fg = theme.green })
vim.api.nvim_set_hl(0, "NoiceCmdlineIconInput", { fg = theme.green })
vim.api.nvim_set_hl(0, "NoiceCmdlineIconSearch", { fg = theme.green })
vim.api.nvim_set_hl(0, "NoiceCmdlineIconLua", { fg = theme.green })
vim.api.nvim_set_hl(0, "NoiceCmdlineIconHelp", { fg = theme.green })
vim.api.nvim_set_hl(0, "NoiceCmdlineIconFilter", { fg = theme.green })
vim.api.nvim_set_hl(0, "NoiceCmdlineIconCalculator", { fg = theme.green })

vim.api.nvim_set_hl(0, "@variable", { fg = theme.white })
vim.api.nvim_set_hl(0, "@variable.builtin", { fg = theme.dark_purple })
vim.api.nvim_set_hl(0, "@variable.parameter", { fg = theme.white })
vim.api.nvim_set_hl(0, "@variable.parameter.builtin", { fg = theme.white })
vim.api.nvim_set_hl(0, "@variable.member", { fg = theme.nord_blue })

vim.api.nvim_set_hl(0, "@constant", { fg = theme.white })
vim.api.nvim_set_hl(0, "@constant.builtin", { fg = theme.dark_purple })
vim.api.nvim_set_hl(0, "@constant.macro", { fg = theme.dark_purple })

vim.api.nvim_set_hl(0, "@module", { fg = theme.yellow })
vim.api.nvim_set_hl(0, "@module.builtin", { fg = theme.yellow })
vim.api.nvim_set_hl(0, "@label", { fg = theme.orange })

vim.api.nvim_set_hl(0, "@string", { fg = theme.green })
vim.api.nvim_set_hl(0, "@string.documentation", { fg = theme.green })
vim.api.nvim_set_hl(0, "@string.regexp", { fg = theme.vibrant_green })
vim.api.nvim_set_hl(0, "@string.escape", { fg = theme.vibrant_green })
vim.api.nvim_set_hl(0, "@string.special", { fg = theme.yellow })
vim.api.nvim_set_hl(0, "@string.special.symbol", { fg = theme.white })
vim.api.nvim_set_hl(0, "@string.special.path", { fg = theme.yellow })
vim.api.nvim_set_hl(0, "@string.special.url", { fg = theme.white, underline = true })

vim.api.nvim_set_hl(0, "@character", { fg = theme.green })
vim.api.nvim_set_hl(0, "@character.special", { fg = theme.yellow })

vim.api.nvim_set_hl(0, "@boolean", { fg = theme.dark_purple })
vim.api.nvim_set_hl(0, "@number", { fg = theme.dark_purple })
vim.api.nvim_set_hl(0, "@number.float", { fg = theme.dark_purple })

vim.api.nvim_set_hl(0, "@type", { fg = theme.yellow })
vim.api.nvim_set_hl(0, "@type.builtin", { fg = theme.yellow })
vim.api.nvim_set_hl(0, "@type.definition", { fg = theme.yellow })

vim.api.nvim_set_hl(0, "@attribute", { fg = theme.dark_purple })
vim.api.nvim_set_hl(0, "@attribute.builtin", { fg = theme.yellow })
vim.api.nvim_set_hl(0, "@property", { fg = theme.nord_blue })

vim.api.nvim_set_hl(0, "@function", { fg = theme.vibrant_green })
vim.api.nvim_set_hl(0, "@function.builtin", { fg = theme.vibrant_green })
vim.api.nvim_set_hl(0, "@function.call", { fg = theme.vibrant_green })
vim.api.nvim_set_hl(0, "@function.macro", { fg = theme.vibrant_green })
vim.api.nvim_set_hl(0, "@function.method", { fg = theme.vibrant_green })
vim.api.nvim_set_hl(0, "@function.method.call", { fg = theme.vibrant_green })

vim.api.nvim_set_hl(0, "@constructor", { fg = theme.vibrant_green })
vim.api.nvim_set_hl(0, "@operator", { fg = theme.orange })

vim.api.nvim_set_hl(0, "@keyword", { fg = theme.red })
vim.api.nvim_set_hl(0, "@keyword.coroutine", { fg = theme.red })
vim.api.nvim_set_hl(0, "@keyword.function", { fg = theme.red })
vim.api.nvim_set_hl(0, "@keyword.operator", { fg = theme.orange })
vim.api.nvim_set_hl(0, "@keyword.import", { fg = theme.red })
vim.api.nvim_set_hl(0, "@keyword.type", { fg = theme.red })
vim.api.nvim_set_hl(0, "@keyword.modifier", { fg = theme.red })
vim.api.nvim_set_hl(0, "@keyword.repeat", { fg = theme.red })
vim.api.nvim_set_hl(0, "@keyword.return", { fg = theme.red })
vim.api.nvim_set_hl(0, "@keyword.debug", { fg = theme.orange })
vim.api.nvim_set_hl(0, "@keyword.exception", { fg = theme.red })
vim.api.nvim_set_hl(0, "@keyword.conditional", { fg = theme.red })
vim.api.nvim_set_hl(0, "@keyword.conditional.ternary", { fg = theme.red })
vim.api.nvim_set_hl(0, "@keyword.directive", { fg = theme.dark_purple })
vim.api.nvim_set_hl(0, "@keyword.directive.define", { fg = theme.dark_purple })

vim.api.nvim_set_hl(0, "@punctuation.delimiter", { fg = theme.light_grey })
vim.api.nvim_set_hl(0, "@punctuation.bracket", { fg = theme.white })
vim.api.nvim_set_hl(0, "@punctuation.special", { fg = theme.nord_blue })

vim.api.nvim_set_hl(0, "@comment", { fg = theme.light_grey })
vim.api.nvim_set_hl(0, "@comment.documentation", { fg = theme.light_grey })
vim.api.nvim_set_hl(0, "@comment.error", { fg = theme.black, bg = theme.red })
vim.api.nvim_set_hl(0, "@comment.warning", { fg = theme.black, bg = theme.yellow })
vim.api.nvim_set_hl(0, "@comment.todo", { fg = theme.black, bg = theme.cyan })
vim.api.nvim_set_hl(0, "@comment.note", { fg = theme.black, bg = theme.vibrant_green })

vim.api.nvim_set_hl(0, "@markup.heading", { fg = theme.orange })
vim.api.nvim_set_hl(0, "@markup.quote", { fg = theme.light_grey })
vim.api.nvim_set_hl(0, "@markup.math", { fg = theme.blue })
vim.api.nvim_set_hl(0, "@markup.link", { fg = theme.green })
vim.api.nvim_set_hl(0, "@markup.link.label", { fg = theme.yellow })
vim.api.nvim_set_hl(0, "@markup.link.url", { fg = theme.nord_blue })
vim.api.nvim_set_hl(0, "@markup.raw", { fg = theme.vibrant_green })
vim.api.nvim_set_hl(0, "@markup.raw.block", { fg = theme.vibrant_green })
vim.api.nvim_set_hl(0, "@markup.list", { fg = theme.nord_blue })
vim.api.nvim_set_hl(0, "@markup.list.unchecked", { fg = theme.light_grey })

vim.api.nvim_set_hl(0, "@diff.plus", { fg = theme.vibrant_green })
vim.api.nvim_set_hl(0, "@diff.minus", { fg = theme.red })
vim.api.nvim_set_hl(0, "@diff.delta", { fg = theme.nord_blue })

vim.api.nvim_set_hl(0, "@tag", { fg = theme.orange })
vim.api.nvim_set_hl(0, "@tag.builtin", { fg = theme.yellow })
vim.api.nvim_set_hl(0, "@tag.delimiter", { fg = theme.vibrant_green })
