[mgr]
prepend_keymap = [
  { on = [
    "g",
    "c",
  ], run = 'cd /Users/crcr/.local/share/chezmoi', desc = "Go to config directory" },
  { on = [
    "g",
    "i",
  ], run = 'plugin lazygit', desc = "run lazygit" },
]
