[mgr]
prepend_keymap = [
  { on = [
    "g",
    "c",
  ], run = 'cd ~/.local/share/chezmoi', desc = "Go to config directory" },
  { on = [
    "g",
    "i",
  ], run = 'plugin lazygit', desc = "run lazygit" },
  { on = [
    "g",
    "D",
  ], run = 'cd ~/Document', desc = "open Document" },
]
