return {
  "crcrworks/crosspond-extra.nvim",
  { import = "crosspond-extra.editing-support.dial" },
  { import = "crosspond-extra.editing-support.neogen" },
  { import = "crosspond-extra.editing-support.wildfire" },
  { import = "crosspond-extra.editing-support.tiny-code-action" },
  { import = "crosspond-extra.editing-support.nvim-treesitter-context" },
  { import = "crosspond-extra.editing-support.treesj" },
  { import = "crosspond-extra.editing-support.surround" },
  { import = "crosspond-extra.integration.kitty" },
  { import = "crosspond-extra.motion.leap" },
  { import = "crosspond-extra.diagnostics.tiny-inline-diagnostic" },
  { import = "crosspond-extra.media.cord" },
  { import = "crosspond-extra.pack.chezmoi" },
  { import = "crosspond-extra.pack.rust" },
  { import = "crosspond-extra.pack.typescript" },
  { import = "crosspond-extra.pack.css" },
  { import = "crosspond-extra.pack.typos" },
  { import = "crosspond-extra.pack.yaml" },
  { import = "crosspond-extra.pack.toml" },
}
