# ["dot_config/nvim"]
# type = "git-repo"
# url = "https://github.com/crcrworks/dotfiles-nvim.git"
#
# ["dot_config/ghostty"]
# type = "git-repo"
# url = "https://github.com/crcrworks/dotfiles-ghostty.git"
#
# ["dot_config/yazi"]
# type = "git-repo"
# url = "https://github.com/crcrworks/dotfiles-yazi.git"
#
# ["dot_config/starship"]
# type = "git-repo"
# url = "https://github.com/crcrworks/dotfiles-starship.git"
#
# ["dot_config/aerospace"]
# type = "git-repo"
# url = "https://github.com/crcrworks/dotfiles-aerospace.git"
#
# ["dot_config/fish"]
# type = "git-repo"
# url = "https://github.com/crcrworks/dotfiles-fish.git"
#
# ["dot_config/sketchybar"]
# type = "git-repo"
# url = "https://github.com/crcrworks/dotfiles-sketchybar.git"
#
# ["dot_config/borders"]
# type = "git-repo"
# url = "https://github.com/crcrworks/dotfiles-borders.git"
