unbind C-b

bind -n C-t new-window -c "#{pane_current_path}"
bind -n C-w 'kill-window'

# Enable 256 color mode
set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'

# Enable mouse
set-option -g mouse on

bind -n C-] next-window
bind -n C-_ previous-window

bind -n 'C--' split-window -vc "#{pane_current_path}"
bind -n 'C-\' split-window -hc "#{pane_current_path}"

bind -n C-S-h select-pane -L
bind -n C-S-j select-pane -D
bind -n C-S-k select-pane -U
bind -n C-S-l select-pane -R

set-option -g status-right ""
set-option -g status-left ""

## COLORSCHEME: everforest dark medium
set -g @everforest_bg_dim '#1e2326'
set -g @everforest_bg0 '#272e33'
set -g @everforest_bg1 '#2e383c'
set -g @everforest_bg2 '#374145'
set -g @everforest_bg3 '#414b50'
set -g @everforest_bg4 '#495156'
set -g @everforest_bg5 '#4f5b58'
set -g @everforest_bg_visual '#4c3743'
set -g @everforest_bg_red '#493b40'

set -g @everforest_fg '#d3c6aa'
set -g @everforest_red '#e67e80'
set -g @everforest_orange '#e69875'
set -g @everforest_yellow '#dbbc7f'
set -g @everforest_green '#a7c080'
set -g @everforest_aqua '#83c092'
set -g @everforest_blue '#7fbbb3'
set -g @everforest_purple '#d699b6'
set -g @everforest_grey0 '#7a8478'
set -g @everforest_grey1 '#859289'
set -g @everforest_grey2 '#9da9a0'
set -g @everforest_statusline1 '#a7c080'
set -g @everforest_statusline2 '#d3c6aa'
set -g @everforest_statusline3 '#e67e80'

set-option -g status "on"
set -g status-interval 2

set-option -g status-fg '#d3c6aa' # fg (No idea why I can't use variables here)
set-option -g status-bg '#272e33' # transparent

set-option -g mode-style fg='#{@everforest_purple}',bg='#{@everforest_bg_red}'

# default statusbar colors
set-option -g status-style fg='#{@everforest_fg}',bg='default',default 

# ---- Formatting ----

set -g window-status-separator '#[fg=#{@everforest_grey2},bg=#{status-bg}]'

set -g window-status-format "#[fg=#{@everforest_grey0},bg=#{status-bg}]  #W  "

set -g window-status-current-format \
"#[fg=default,bg=#{status-bg}]\
#[fg=#{@everforest_aqua},bg=#{status-bg}]\
#[fg=#{status-bg},bg=#{@everforest_aqua}] #W \
#[fg=#{@everforest_aqua},bg=#{status-bg}]\
#[fg=default,bg=#{status-bg}]"
