unbind C-b

bind -n C-t new-window -c "#{pane_current_path}"
bind -n C-w 'kill-window'

# Enable 256 color mode
set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'

# Enable mouse
set-option -g mouse on

bind -n C-] next-window
bind -n C-_ previous-window

bind -n 'C--' split-window -vc "#{pane_current_path}"
bind -n 'C-\' split-window -hc "#{pane_current_path}"

bind -n C-S-h select-pane -L
bind -n C-S-j select-pane -D
bind -n C-S-k select-pane -U
bind -n C-S-l select-pane -R

set-option -g status-right ""
set-option -g status-left ""

## COLORSCHEME: everforest dark medium
set -g @everforest_bg_dim '#232a2e'
set -g @everforest_bg0 '#2d353b'
set -g @everforest_bg1 '#343f44'
set -g @everforest_bg2 '#3d484d'
set -g @everforest_bg3 '#475258'
set -g @everforest_bg4 '#4f585e'
set -g @everforest_bg5 '#56635f'
set -g @everforest_bg_visual '#543a48'
set -g @everforest_bg_red '#514045'
set -g @everforest_bg_green '#425047'
set -g @everforest_bg_blue '#3a515d'
set -g @everforest_bg_yellow '#4d4c43'

set -g @everforest_fg '#d3c6aa'
set -g @everforest_red '#e67e80'
set -g @everforest_orange '#e69875'
set -g @everforest_yellow '#dbbc7f'
set -g @everforest_green '#a7c080'
set -g @everforest_aqua '#83c092'
set -g @everforest_blue '#7fbbb3'
set -g @everforest_purple '#d699b6'
set -g @everforest_grey0 '#7a8478'
set -g @everforest_grey1 '#859289'
set -g @everforest_grey2 '#9da9a0'
set -g @everforest_statusline1 '#a7c080'
set -g @everforest_statusline2 '#d3c6aa'
set -g @everforest_statusline3 '#e67e80'

set-option -g status "on"
set -g status-interval 2

set-option -g status-fg '#d3c6aa' # fg (No idea why I can't use variables here)
set-option -g status-bg '#232a2e' # bg0

set-option -g mode-style fg='#{@everforest_purple}',bg='#{@everforest_bg_red}' # fg=purple, bg=bg_visual

# default statusbar colors
set-option -g status-style fg='#{@everforest_fg}',bg='#{@everforest_bg_dim}',default # fg=fg bg=bg_dim

# ---- Formatting ----

set -g window-status-separator '#[fg=#{@everforest_grey2},bg=#{@everforest_bg_dim}]'

set -g window-status-format "#[fg=#{@everforest_grey0},bg=#{@everforest_bg_dim}]  #W  "

set -g window-status-current-format \
"#[fg=default,bg=#{@everforest_bg_dim}]\
#[fg=#{@everforest_aqua},bg=#{@everforest_bg_dim}]\
#[fg=#{@everforest_bg_dim},bg=#{@everforest_aqua}] #W \
#[fg=#{@everforest_aqua},bg=#{@everforest_bg_dim}]\
#[fg=default,bg=#{@everforest_bg_dim}]"
