[shell_alias]
"o" = "open ."
"x" = "exit"
"cl" = "clear"
"emacs" = "emacs -nw"
"intel" = "arch -x86_64 bash"
"bb" = "bartib"
"co" = "colima"
"beep" = "afplay /System/Library/Sounds/Ping.aiff"
"killwine" = "killall -9 wineserver && killall -9 wine64-preloader"
"lq" = "lazysql"
"l" = "clear && ls"
"lg" = "lazygit"
"gl" = "git log --oneline --graph --all"
"yt" = "yt-dlp"
"port" = "lsof"
"vencode-install" = "open /Users/crcr/Development/installer/VencordInstaller\\ 5.app"
"nv" = "nvim"
"ca" = "cargo"
"oc" = "opencode"

"ju" = "mise exec jj -- jj"
"jua" = "clear && ju -r.."
"jus" = "ju status"
"jub" = "ju bookmark"
"jubl" = "ju bookmark list"
"jubd" = "ju bookmark delete"
"jubs" = "ju bookmark set"
"jubs-" = "ju bookmark set -r @-"
"jubm" = "ju bookmark move"
"jubt" = "ju bookmark track"
"jur" = "ju rebase"
"jun" = "ju new"
"jud" = "ju desc -m"
"juc" = "ju commit -m"
"jue" = "ju edit"
"judi" = "ju diff"
"jug" = "ju git"
"jugp" = "ju git push"
"jugf" = "ju git fetch"

"Ju" = "mise exec jj -- jj"
"Jua" = "ju -r.."
"Jus" = "ju status"
"Jub" = "ju bookmark"
"Jubl" = "ju bookmark list"
"Jubd" = "ju bookmark delete"
"Jubs" = "ju bookmark set"
"Jubs-" = "ju bookmark set -r @-"
"Jubm" = "ju bookmark move"
"Jubm-" = "ju bookmark move -r @-"
"Jubt" = "ju bookmark track"
"Jur" = "ju rebase"
"Jun" = "ju new"
"Jud" = "ju desc -m"
"Juc" = "ju commit -m"
"Jue" = "ju edit"
"Judi" = "ju diff"
"Jug" = "ju git"
"Jugp" = "ju git push"
"Jugf" = "ju git fetch"

"apps" = "yabai -m query --windows | jq '.[] | {app}'"

"bl" = "brew list --formula"
"bg" = "brew upgrade"
"blc" = "brew list --cask"
"al" = "echo \"************brew***************\"; brew list --formula; echo \"************cask***************\"; brew list --cask; echo \"************mas***************\"; mas list"
"ao" = "echo \"************brew***************\"; brew upgrade --dry-run; echo \"************cask***************\"; brew upgrade --cask --greedy --dry-run; echo \"************mas***************\"; mas outdated"
"ag" = "echo \"************brew***************\"; brew upgrade; echo \"************cask***************\"; brew upgrade --cask --greedy; echo \"************mas***************\"; mas upgrade"

".." = "cd .."
"..." = "cd ../.."
"...." = "cd ../../.."
"ei" = "eza --icons --git"
"ea" = "eza -a --icons --git"
"ee" = "eza -aahl --icons --git"
"et" = "eza -T -L 3 -a -I 'node_modules|.git|.cache' --icons"
"eta" = "eza -T -a -I 'node_modules|.git|.cache' --color=always --icons | less -r"
"ls" = "ei"
"Ls" = "ei"
"la" = "ea"
"ll" = "ee"
"lt" = "et"
"lta" = "eta"

"ch" = "chezmoi"
"cha" = "chezmoi apply"
"chc" = "chezmoi cd"

"ld" = "lazydocker"
"dkl" = "docker logs -f"
"dke" = "docker exec"
"dkc" = "docker compose"
"dkcl" = "docker compose logs"
"dkcu" = "docker compose up -d"
"dkcd" = "docker compose down"
"dkcub" = "docker compose up -d --build"
"dkcb" = "docker compose build"

"dllobby" = "docker logs -f lobby"
"delobby" = "docker exec -i lobby rcon-cli"
"dlnijisaba" = "docker logs -f nijisaba"
"denijisaba" = "docker exec -i nijisaba rcon-cli"
"dlsubworld" = "docker logs -f subworld"
"desubworld" = "docker exec -i subworld rcon-cli"
"dlvelocity" = "docker logs -f velocity"

"gs" = "git status"
"gfa" = "git fetch --all"
"gpa" = "git pull --all"
"gco" = "git checkout"
"gcob" = "git checkout -b"
"gsu" = "git stash save -u"
"gsl" = "git stash list"
"gsc" = "git stash clear"
"gb" = "git branch --all"
"gbl" = "git branch"
"gbr" = "git branch --remote"

"nrb" = "npm run build"
"nrw" = "npm run watch"
"nrt" = "npm run test"
"nig" = "npm install -g"
"nid" = "npm install -D"
"pnd" = "pnpm dev"

"ccmake" = "cp ~/.config/fish/template/cmake.txt ./CMakeLists.txt"
"ccmakee" = "cp ~/.config/fish/template/cmake-eggx.txt ./CMakeLists.txt"
"cclangd" = "cp ~/.config/fish/template/clangd.txt ./.clangd"
