return {
  override = {
    DiagnosticUnderlineOk = { undercurl = true, sp = "green" },
    DiagnosticUnderlineHint = { undercurl = true, sp = "vibrant_green" },
    DiagnosticUnderlineInfo = { undercurl = true, sp = "nord_blue" },
    DiagnosticUnderlineWarn = { undercurl = true, sp = "yellow" },
    DiagnosticUnderlineError = { undercurl = true, sp = "red" },

    LspCodelens = { fg = "light_grey" },

    NvimTreeFolderName = { fg = "nord_blue" },
    NvimTreeEmptyFolderName = { fg = "nord_blue" },
    NvimTreeOpenedFolderName = { fg = "nord_blue" },
    NvimTreeFolderIcon = { fg = "nord_blue" },
    NvimTreeFolderArrowOpen = { fg = "nord_blue" },
    NvimTreeCutHL = { undercurl = true, sp = "purple" },
    NvimTreeCopiedHL = { undercurl = true, sp = "nord_blue" },
    NvimTreeBookmarkHL = { undercurl = true, sp = "green" },

    SpellBad = { undercurl = true, sp = "orange" },
    SpellCap = { undercurl = true, sp = "yellow" },
    SpellRare = { undercurl = true, sp = "nord_blue" },
    SpellLocal = { undercurl = true, sp = "green" },

    String = { fg = "vibrant_green", link = "" },
    Include = { fg = "red" },

    ["@variable"] = { fg = "white" },
    ["@variable.builtin"] = { fg = "dark_purple" },
    ["@variable.parameter"] = { fg = "white" },
    ["@variable.parameter.builtin"] = { fg = "white" },
    ["@variable.member"] = { fg = "nord_blue" },

    ["@constant"] = { fg = "white" },
    ["@constant.builtin"] = { fg = "dark_purple" },
    ["@constant.macro"] = { fg = "dark_purple" },

    ["@module"] = { fg = "yellow" },
    ["@module.builtin"] = { fg = "yellow" },
    ["@label"] = { fg = "orange" },

    ["@string"] = { fg = "green" },
    ["@string.documentation"] = { fg = "green" },
    ["@string.regexp"] = { fg = "vibrant_green" },
    ["@string.escape"] = { fg = "vibrant_green" },
    ["@string.special"] = { fg = "yellow" },
    ["@string.special.symbol"] = { fg = "white" },
    ["@string.special.path"] = { fg = "yellow" },
    ["@string.special.url"] = { fg = "white", underline = true },

    ["@character"] = { fg = "green" },
    ["@character.special"] = { fg = "yellow" },

    ["@boolean"] = { fg = "dark_purple" },
    ["@number"] = { fg = "dark_purple" },
    ["@number.float"] = { fg = "dark_purple" },

    ["@type"] = { fg = "yellow" },
    ["@type.builtin"] = { fg = "yellow" },
    ["@type.definition"] = { fg = "yellow" },

    ["@attribute"] = { fg = "dark_purple" },
    ["@attribute.builtin"] = { fg = "yellow" },
    ["@property"] = { fg = "nord_blue" },

    ["@function"] = { fg = "vibrant_green" },
    ["@function.builtin"] = { fg = "vibrant_green" },
    ["@function.call"] = { fg = "vibrant_green" },
    ["@function.macro"] = { fg = "vibrant_green" },
    ["@function.method"] = { fg = "vibrant_green" },
    ["@function.method.call"] = { fg = "vibrant_green" },

    ["@constructor"] = { fg = "vibrant_green" },
    ["@operator"] = { fg = "orange" },

    ["@keyword"] = { fg = "red" },
    ["@keyword.coroutine"] = { fg = "red" },
    ["@keyword.function"] = { fg = "red" },
    ["@keyword.import"] = { fg = "red" },

    ["@keyword.type"] = { fg = "red" },
    ["@keyword.modifier"] = { fg = "red" },
    ["@keyword.repeat"] = { fg = "red" },
    ["@keyword.return"] = { fg = "red" },
    ["@keyword.debug"] = { fg = "orange" },
    ["@keyword.exception"] = { fg = "red" },
    ["@keyword.conditional"] = { fg = "red" },
    ["@keyword.conditional.ternary"] = { fg = "red" },
    ["@keyword.directive"] = { fg = "dark_purple" },
    ["@keyword.directive.define"] = { fg = "dark_purple" },

    ["@punctuation.delimiter"] = { fg = "light_grey" },
    ["@punctuation.bracket"] = { fg = "white" },
    ["@punctuation.special"] = { fg = "nord_blue" },

    ["@comment"] = { fg = "light_grey" },
    ["@comment.documentation"] = { fg = "light_grey" },
    ["@comment.error"] = { fg = "black", bg = "red" },
    ["@comment.warning"] = { fg = "black", bg = "yellow" },
    ["@comment.todo"] = { fg = "black", bg = "cyan" },
    ["@comment.note"] = { fg = "black", bg = "vibrant_green" },

    ["@markup.heading"] = { fg = "orange" },
    ["@markup.quote"] = { fg = "light_grey" },
    ["@markup.math"] = { fg = "blue" },
    ["@markup.link"] = { fg = "green" },
    ["@markup.link.label"] = { fg = "yellow" },
    ["@markup.link.url"] = { fg = "nord_blue" },
    ["@markup.raw"] = { fg = "vibrant_green" },
    ["@markup.raw.block"] = { fg = "vibrant_green" },
    ["@markup.list"] = { fg = "nord_blue" },
    ["@markup.list.unchecked"] = { fg = "light_grey" },

    ["@diff.plus"] = { fg = "vibrant_green" },
    ["@diff.minus"] = { fg = "red" },
    ["@diff.delta"] = { fg = "nord_blue" },

    ["@tag"] = { fg = "orange" },
    ["@tag.builtin"] = { fg = "yellow" },
    ["@tag.delimiter"] = { fg = "vibrant_green" },
  },
  add = {
    SnacksPickerBorder = { fg = "black" },
    SnacksPickerCol = { fg = "vibrant_green" },
    SnacksPickerDesc = { fg = "vibrant_green" },
    SnacksPickerTree = { fg = "vibrant_green" },
    SnacksPickerDir = { fg = "white" },
    SnacksPickerFile = { fg = "orange" },
    SnacksPickerMatch = { fg = "orange" },
    SnacksDashboardDir = { fg = "white" },
    SnacksDashboardFile = { fg = "yellow" },
    SnacksDashboardIcon = { fg = "yellow" },
    SnacksDashboardTitle = { fg = "orange" },
    SnacksDashboardHeader = { fg = "orange" },
    SnacksDashboardFooter = { fg = "orange" },
    SnacksDashboardDesc = { fg = "orange" },
    SnacksDashboardSpecial = { fg = "yellow" },

    NoiceCmdlinePopupBorder = { fg = "green" },
    NoiceCmdlineIconCmdline = { fg = "green" },
    NoiceCmdlineIconInput = { fg = "green" },
    NoiceCmdlineIconSearch = { fg = "green" },
    NoiceCmdlineIconLua = { fg = "green" },
    NoiceCmdlineIconHelp = { fg = "green" },
    NoiceCmdlineIconFilter = { fg = "green" },
    NoiceCmdlineIconCalculator = { fg = "green" },
  },
}
