[settings]
experimental = true
idiomatic_version_file_enable_tools = ["rust"]

[tools]
# skhdとyabaiはややこしいのでmiseでは管理しない
"rust" = { version = "stable", components = "rust-src,llvm-tools,rust-analyzer" }
"go" = "latest"
"python" = "latest"
"node" = "22"
"bun" = "latest"
"uv" = "latest"
"pnpm" = "latest"
"typst" = "latest"
"jq" = "latest"
"yq" = "latest"
"zoxide" = "latest"
"aqua:neovim/neovim" = "latest"
"dust" = "latest"
"has" = "latest"
"tree-sitter" = "latest"
"jj" = "latest"
"gh" = "latest"
"chezmoi" = "latest"
"cargo:eza" = "latest"
"ghq" = "latest"
"yazi" = "latest"
"fzf" = "latest"
"fastfetch" = "latest"
"cargo-binstall" = "latest"
"starship" = "latest"
"task" = "latest"
"just" = "latest"
"act" = "latest"
"github:anomalyco/opencode" = "latest"
"prek" = "latest"
"yt-dlp" = "latest"
"npm:openclaw" = "latest"
"go:github.com/pranshuparmar/witr/cmd/witr" = "latest"
"wrangler" = "latest"
"lazydocker" = "latest"
"jjui" = "latest"
"ripgrep" = "latest"
"bat" = "latest"
"github:asmvik/yabai" = "latest"
"github:tumf/jj-desc" = "latest"

# Language Servers
"github:vadimcn/codelldb" = "latest"
"lua-language-server" = "latest"
"stylua" = "latest"
"github:Kampfkarren/selene" = "latest"
"tombi" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"ruff" = "latest"
"biome" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:emmet-ls" = "latest"
"npm:@typescript/native-preview" = "latest"

[hooks]
postinstall = "npx corepack enable"

[tasks."brew-install"]
run = "Brew bundle"
