prSections:
- title: Pull Requests
  filters: is:open
- title: My Pull Requests
  filters: is:open author:@me
- title: Needs My Review
  filters: is:open review-requested:@me
- title: Involved
  filters: is:open involves:@me -author:@me
issuesSections:
- title: Issues
  filters: is:open
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved
  filters: is:open involves:@me -author:@me
theme:
  colors:
    text:
      primary: "#D3C6AA"
      secondary: "#69a59d"
      inverted: "#F7F1FF"
      faint: "#656d73"
      warning: "#e67e80"
      success: "#83c092"
    background:
      selected: "#656d73"
    border:
      primary: "#656d73"
      secondary: "#626a70"
      faint: "#656d73"
