theme:
  colors:
    text:
      primary: "#D3C6AA"
      secondary: "#69a59d"
      inverted: "#F7F1FF"
      faint: "#3a4248"
      warning: "#e67e80"
      success: "#83c092"
    background:
      selected: "#656d73"
    border:
      primary: "#656d73"
      secondary: "#626a70"
      faint: "#3a4248"

