backtraces_path = "/path/to/neovide_backtraces.log"  # see below for the default platform specific location
fork = false
frame = "buttonless"
idle = true
maximized = false
mouse-cursor-icon = "arrow"
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false
neovim-bin = "/opt/homebrew/bin/nvim"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "W300" }
size = 16.0

[box-drawing.sizes]
default = [0, 0]

