#!/bin/bash

# by default, tile all windows
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

# mouse settings
yabai -m config mouse_follows_focus on

yabai -m config mouse_modifier ctrl
# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

yabai -m mouse_drop_action swap

yabai -m rule --add app="^System Settings$" layer=above manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Spotify$" space=6
yabai -m rule --add app="^Discord$" space=5

yabai -m config window_shadow on \
                window_opacity off \
                mouse_follows_focus off \
                window_animation_duration 0.15 \ 
                window_animation_easing ease_in_out_quart \
                mouse_follows_focus on \
                focus_follows_mouse autoraise

yabai -m signal --add event=window_destroyed active=yes action="yabai -m window --focus recent || yabai -m window --focus recent"
