[shell_alias]
"o" = "open ."
"x" = "exit"
"cl" = "clear"
"emacs" = "emacs -nw"
"intel" = "arch -x86_64 bash"
"bb" = "bartib"
"co" = "colima"
"beep" = "afplay /System/Library/Sounds/Ping.aiff"
"killwine" = "killall -9 wineserver && killall -9 wine64-preloader"
"lq" = "lazysql"
"l" = "clear && ls"
"lg" = "lazygit"
"gl" = "git log --oneline --graph --all"
"yt" = "yt-dlp"
"port" = "lsof"
"vencode-install" = "open /Users/crcr/Development/installer/VencordInstaller\\ 5.app"
"nv" = "nvim"
"ca" = "cargo"
"oc" = "opencode"
"apps" = "yabai -m query --windows | jq '.[] | {app}'"
