[shell_alias]
"ju" = "mise exec jj -- jj"
"jua" = "clear && ju -r.."
"jus" = "ju status"
"jub" = "ju bookmark"
"jubl" = "ju bookmark list"
"jubd" = "ju bookmark delete"
"jubs" = "ju bookmark set"
"jubs-" = "ju bookmark set -r @-"
"jubm" = "ju bookmark move"
"jubt" = "ju bookmark track"
"jur" = "ju rebase"
"jun" = "ju new"
"jud" = "ju desc -m"
"juc" = "ju commit -m"
"jue" = "ju edit"
"judi" = "ju diff"
"jug" = "ju git"
"jugp" = "ju git push"
"jugf" = "ju git fetch"

"Ju" = "mise exec jj -- jj"
"Jua" = "ju -r.."
"Jus" = "ju status"
"Jub" = "ju bookmark"
"Jubl" = "ju bookmark list"
"Jubd" = "ju bookmark delete"
"Jubs" = "ju bookmark set"
"Jubs-" = "ju bookmark set -r @-"
"Jubm" = "ju bookmark move"
"Jubm-" = "ju bookmark move -r @-"
"Jubt" = "ju bookmark track"
"Jur" = "ju rebase"
"Jun" = "ju new"
"Jud" = "ju desc -m"
"Juc" = "ju commit -m"
"Jue" = "ju edit"
"Judi" = "ju diff"
"Jug" = "ju git"
"Jugp" = "ju git push"
"Jugf" = "ju git fetch"
