[tools]
# skhdとyabaiはややこしいのでmiseでは管理しない

"rust" = { version = "stable", components = "rust-src,llvm-tools,rust-analyzer" }
"go" = "latest"
"python" = "latest"
"node" = "24"
"pnpm" = "latest"
"bun" = "latest"
"uv" = "latest"
"typst" = "latest"
"jq" = "latest"
"yq" = "latest"
"zoxide" = "latest"
"aqua:neovim/neovim" = "latest"
"dust" = "latest"
"has" = "latest"
"tree-sitter" = "latest"
"jj" = "latest"
"gh" = "latest"
"chezmoi" = "latest"
"cargo:eza" = "latest"
"ghq" = "latest"
"yazi" = "latest"
"fzf" = "latest"
"fastfetch" = "latest"
"cargo-binstall" = "latest"
"starship" = "latest"
"task" = "latest"
"act" = "latest"
"github:anomalyco/opencode" = "latest"
"prek" = "latest"
"yt-dlp" = "latest"
"npm:openclaw" = "latest"
"go:github.com/pranshuparmar/witr/cmd/witr" = "latest"
"wrangler" = "latest"
"lazydocker" = "latest"
"jjui" = "latest"
"ripgrep" = "latest"
"bat" = "latest"
"github:Rtarun3606k/TakaTime" = "latest"
"github:AlDanial/cloc" = "latest"
"llmfit" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:svelte-language-server" = "latest"
"github:tumf/jj-desc" = "latest"
